### ISSUE TITLE
2016年总结

### ISSUE THREAD

**Issue by cjuexuan** [cjuexuan/mynote#23]
# 2016

### 工作

1. 从传统软件到互联网，来到魔都，公司技术氛围更加浓厚了
2. 貌似生产环境今年所有的代码都是scala写的，lightbend的三大利器都简单用了一下
3. 独立开发了个有意义的项目:[xql](https://github.com/cjuexuan/mynote/issues/21)
4. 独立解决问题的能力比今年年初提高了，遇到问题源码阅读的经验得到了成长
5. 基本围绕的都是大数据和并发编程这一块

### 社区

1. 参加了几次spark meetup和jug，还得到了一堆书，不得不说北上广深的技术氛围还是比其他地方好很多
2. 给spark报了两个issue，提了一个pull request
3. [github](https://github.com/cjuexuan)的followers终于到35了，[blog](http://blog.csdn.net/cjuexuan)访问也超过了3w
4. 自己本来想开源的项目还没开源成功,这点还是蛮遗憾的

### 书单

- [x] programming scala
- [x] scala cookbook
- [x] functional programming in scala
- [x] reactive messaging patterns with the actor model
- [x] 微服务设计
- [x] functional thinking 
- [x] netty in action
- [x] 写给大忙人看的java8
- [x] 代码之髓
- [x] 深入理解java虚拟机第二版
- [ ] 魔力haskell
- [ ] haskell函数式编程入门
- [x] java性能权威指南

### 办公环境

今年把办公外设提升了一个档次

![work](http://7xnz7j.com1.z0.glb.clouddn.com/14831778700014.jpg)

### 人生大事

1. 去她家见了一下家长，哈哈 
2. 答应陪她去西藏，却没完成

### 房子

1. 买房后成为百万负翁了，不过一桩心事终于落定了

### 其他

身体素质感觉还是下降了挺多，以后还是要多锻炼，不然程序员这个职业太危险了

## todo

- [x] 买张更舒服的椅子
- [x] 换个手机
- [ ] 把书单完成，不得不说今年书单完成情况还是很差的
- [x] 明年按照现在规划应该主要做大数据平台监控这一块，今年只是简单做了下，压力还是有的
- [ ] 好好学一下haskell
- [ ] 和她去西藏

**Comment by afredlyj** [comment]
666，一年能看这么多书

**Comment by jellyabd** [comment]
厉害了！要多多学习

**Comment by duobei** [comment]
我擦 issues 用来做博客用还是蛮爽的
