### ISSUE TITLE
2017年总结

### ISSUE THREAD

**Issue by cjuexuan** [cjuexuan/mynote#48]
# 2017 

### 工作

1. 今年基本主要的精力都投在了spoor(大数据领域的监控的轮子，通用的现代的监控框架)，终于在新年的最后一天，在自己心目中的deadLine发了1.0.6版本
2. 去年的轮子XQL今年的推广工作做的还可以，目前一天5k+的任务，日活也有100多（主要使用人群还是分析师，数仓，开发，产品)
3. 兼职的运维工作做的还不错，一些诡异异常的分析都能独立完成
4. XQL也成功的实现了多活的架构升级，不过主要维护者已经不是我了，感谢团队小伙伴的努力，23333
5. title也变成了大数据高级开发工程师，送给马上24岁的自己一些掌声

### 社区

1. 首先非常感谢公司，给了我一个去GITC上分享XQL的机会，另外今年也做了两次公司内的XQL分享
2. 有时间参加的社区交流基本也参加了，认识了更多的新朋友
3. 收到过别人的感谢邮件，自己的文章能帮别人解决问题，这点还是非常开心的
4. [github](https://github.com/cjuexuan) follower过100了，掌声在哪里？
5. 帮忙review的netty in action出版了

### 书单

- [x] 代码整洁之道
- [x] 重构
- [x] 编程珠玑
- [x] go in action
- [x] functional and reactive domain modeling
- [x] scala desgin pattern
- [x] 高性能scala
- [x] 分布式一致原理与实践
- [x] learning fp in scala
- [ ] n本未完成的haskell的书(n > 1 )  :(
- [ ] erlang趣学指南
- [x] head first设计模式
- [ ] go程序设计语言
- [ ] 垃圾回收算法手册

### 办公环境

1. 感谢妹子送的键盘托
2. 买了个bose qc25，世界安静了
3. 买了张椅子，把公司的椅子换了，毕竟坐的时间太长了

### 人生大事

1. 妹子来上海了，开心
2. 今年时间真是扯，一个地方都没去 :(

### 其他

1. 和公司同事参加的上海互联网足球联赛拿了精英组的亚军
2. 减肥大计没完成

## 多图环节
![装备](http://7xnz7j.com1.z0.glb.clouddn.com/15147099033263.jpg)
![gitc](http://7xnz7j.com1.z0.glb.clouddn.com/15147082938202.jpg)
![git](http://7xnz7j.com1.z0.glb.clouddn.com/15147084168156.jpg)
![钉钉](http://7xnz7j.com1.z0.glb.clouddn.com/15147084351912.jpg)
![idea](http://7xnz7j.com1.z0.glb.clouddn.com/15147085493615.jpg)
![cloc](http://7xnz7j.com1.z0.glb.clouddn.com/15147087019009.jpg)
![椅子](http://7xnz7j.com1.z0.glb.clouddn.com/15147091886652.jpg)
![足球](http://7xnz7j.com1.z0.glb.clouddn.com/15147095907457.jpg)

## TODO

- [ ] 完善spoor，从0到1简单，从1到10很难，但很难也要做
- [ ] 书单书单书单
- [ ] 抽时间出去玩一趟
- [ ] 争取早日开源spoor和XQL

**Comment by Aaaaaaron** [comment]
@cjuexuan 你好呀, 我公司是 kyligence, 是 Apache kylin 背后的商业公司, 我们也在浦软(上海市浦东新区亮秀路112号Y1座405),  18698518695 这是我微信, 方便加个好友嘛, 还能串串门讨论讨论学习交流一下.
